/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c EAPDaemonAdapter -a eapdaemonadapter.h:eapdaemonadapter.cpp com.qh3client.EAPDaemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef EAPDAEMONADAPTER_H_1368845053
#define EAPDAEMONADAPTER_H_1368845053

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.qh3client.EAPDaemon
 */
class EAPDaemonAdapter: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.qh3client.EAPDaemon")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.qh3client.EAPDaemon\">\n"
"    <signal name=\"Message\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"msg\"/>\n"
"    </signal>\n"
"    <signal name=\"Status\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"statno\"/>\n"
"    </signal>\n"
"    <method name=\"Login\">\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"userinfo\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"Logoff\"/>\n"
"    <method name=\"HasLogin\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"LoginUser\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    EAPDaemonAdapter(QObject *parent);
    virtual ~EAPDaemonAdapter();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool HasLogin();
    void Login(const QVariantMap &userinfo);
    QString LoginUser();
    void Logoff();
Q_SIGNALS: // SIGNALS
    void Message(const QString &msg);
    void Status(int statno);
};

#endif
