/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -c EAPDaemonInterface -p eapdaemoninterface.h:eapdaemoninterface.cpp ../auth/com.qh3client.EAPDaemon.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "eapdaemoninterface.h"

/*
 * Implementation of interface class EAPDaemonInterface
 */

EAPDaemonInterface::EAPDaemonInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

EAPDaemonInterface::~EAPDaemonInterface()
{
}

