#!/bin/sh

### BEGIN INIT INFO
# Provides: qh3client-daemon
# Required-Start: $all
# Required-Stop: $all
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start Daemon of qh3client
# Description: Start Daemon of qh3client, privide dbus support
### END INIT INFO

PATH_TO_PYTHON=/usr/bin/python

case "$1" in
    start)
        /usr/bin/qh3client-daemon start
        ;;
    stop)
        /usr/bin/qh3client-daemon stop
        ;;
    restart)
        /usr/bin/qh3client-daemon restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac
